### ISSUE TITLE
As a user, I want to view products, so I can find products to buy.

### ISSUE THREAD

**Issue by JoeWeate** [bita2019/lnd8-BShade-finalproject#7]
Tasks:
- [x]  Create Mock Product Data
- [x] FE - Create React App
- [x] FE - Add React-Router to React App
- [x] FE - Create /home view to render all products
- [x] BE - Create Inventory Database
- [x] BE - Create Express Server
- [x] BE - Create and expose GET /inventory endpoint
- [x] BE - Add Mock Product Data to Inventory database
- [x] FE - Tie in GET /inventory 
- [x] BE - Use DB data in /inventory endpoint

**Comment by AmarachiOkereke** [comment]
This task has been completed
