### ISSUE TITLE
As a user, I want to add products to my cart, so that I can purchase more than one product at a time.

### ISSUE THREAD

**Issue by JoeWeate** [bita2019/lnd8-BShade-finalproject#9]
- [x] FE add button to add products to cart
- [x] FE add cart icon with number of products that are in the cart
- [x] FE add checkout page with list of products in cart
- [x] FE add delete button to products on checkout page which removes products from cart

**Comment by AmarachiOkereke** [comment]
I have completed all tasks on this issue
